[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[build]
command = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
command = "hypercorn main:app --bind 0.0.0.0:${PORT} --timeout 120"
